import "./globals.css";
import 'react-date-range/dist/styles.css'; // main css file
import 'react-date-range/dist/theme/default.css'; // theme css file


import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NavBar } from "@/components/layout/NavBar";

const inter = Poppins({
  weight: "400",
  subsets: ["latin"],
});
import StateProvider from "@/components/provider/StateProvider";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StateProvider>
      <html lang="en">
        <body className={`flex flex-col ${inter.className}`}>
          <header>
            <NavBar />
          </header>
          <main className="mt-20 min-h-screen">{children}</main>
          <Footer />
        </body>
      </html>
    </StateProvider>
  );
}
