export interface Room {
    room_id?: Number,
    start_date?: string,
    end_date?: string,
    id: Number,
    name: string,
    image1: string,
    image2: string,
    image3: string,
    image4: string,
    image5: string,
    image6: string,
    description: string,
    services: string,
    capacity: Number,
    bedNumber: Number,
    status: Boolean,
    price: Number,
}